export const CLASS_DETAILS = {
  "basic-korean": {
    title: "Basic Korean",
    image: "/Classes Documentation/Basic Korean/IMG_5026.JPG",
    level: "Beginner",
    summary:
      "Start from Hangul to everyday phrases. The class focuses on pronunciation, basic grammar, and daily conversations.",
    highlights: ["Hangul mastery", "Daily expressions", "Pronunciation drills", "Interactive roleplay"],
    schedule: "Tue & Fri",
    time: "14:00 - 18:00",
    duration: "14 weeks",
    location: "Mataram University",
    rating: 4.9,
    tutor: {
      name: "Kim Jin Young",
      role: "Korean Language Tutor",
      image: "/images/fitry.png",
      bio: "Specializes in beginner learners with engaging, step-by-step lessons and speaking practice.",
    },
    documentation: [
      "/Classes Documentation/Basic Korean/8cfbb38f-6c43-45f7-9512-d27d54ed1d2f.JPG",
      "/Classes Documentation/Basic Korean/IMG-20251021-WA0037.jpg",
      "/Classes Documentation/Basic Korean/IMG_3199.jpg",
      "/Classes Documentation/Basic Korean/IMG_5026.JPG",
      "/Classes Documentation/Basic Korean/IMG_8477.JPG",
      "/Classes Documentation/Basic Korean/IMG_8699.JPG",
    ],
  },
  "eps-topik": {
    title: "EPS TOPIK",
    image: "/Classes Documentation/EPS TOPIC/0cae1036-7028-408a-963d-13bb39fee55f.JPG",
    level: "Intermediate",
    summary: "Focused EPS-TOPIK preparation with targeted practice and structured guidance.",
    highlights: ["Mock tests", "Grammar clinics", "Listening drills", "Exam strategies"],
    schedule: "Wed & Fri",
    time: "14:00 - 16:00",
    duration: "14 weeks",
    location: "Mataram University",
    rating: 4.8,
    tutor: {
      name: "Meuttia",
      role: "TOPIK Coach",
      image: "/images/jim.png",
      bio: "Exam-oriented coach with a focus on timing, accuracy, and TOPIK question patterns.",
    },
    documentation: [
      "/Classes Documentation/EPS TOPIC/0cae1036-7028-408a-963d-13bb39fee55f.JPG",
      "/Classes Documentation/EPS TOPIC/19a0812c-e4a8-49f1-be19-9822116880e5.JPG",
      "/Classes Documentation/EPS TOPIC/2ed19799-1561-4935-8a14-14152f916b2f.jpg",
      "/Classes Documentation/EPS TOPIC/31197c40-e8a2-40c6-8e03-8a70650dc936.JPG",
      "/Classes Documentation/EPS TOPIC/4bef2d35-246d-4698-a484-38e3f8252f45.JPG",
      "/Classes Documentation/EPS TOPIC/a39b9bb8-821b-44bf-9c2c-2046c2256864.JPG",
    ],
  },
  "korean-for-tourism": {
    title: "Korean for Tourism",
    image: "/Classes Documentation/KFT/IMG_5624.JPG",
    level: "Beginner - Intermediate",
    summary: "Practical Korean for guiding, hospitality, and travel-related services.",
    highlights: ["Service phrases", "Tour guiding", "Customer handling", "Situational dialogs"],
    schedule: "Fri & Sat",
    time: "16:00 - 18:00",
    duration: "14 weeks",
    location: "Mataram University",
    rating: 4.7,
    tutor: {
      name: "Jung Shua",
      role: "Tourism Language Tutor",
      image: "/images/nad.png",
      bio: "Emphasizes scenario-based learning to build confidence in real-world tourism settings.",
    },
    documentation: [
      "/Classes Documentation/KFT/IMG_5624.JPG",
      "/Classes Documentation/KFT/IMG_5635.JPG",
      "/Classes Documentation/KFT/IMG_5980.JPG",
      "/Classes Documentation/KFT/IMG_6531.JPG",
      "/Classes Documentation/KFT/IMG_7189.JPG",
      "/Classes Documentation/KFT/IMG_7793.JPG",
    ],
  },
  "korean-for-business": {
    title: "Korean for Business",
    image: "/Classes Documentation/KFB/IMG_5215.JPG",
    level: "Intermediate",
    summary: "Professional Korean for workplace communication, meetings, and formal writing.",
    highlights: ["Business emails", "Meeting phrases", "Presentation practice", "Formal vocabulary"],
    schedule: "Fri & Sat",
    time: "16:00 - 18:00 & 13:00 - 15:00",
    duration: "14 weeks",
    location: "Mataram University",
    rating: 4.8,
    tutor: {
      name: "Jung Shua",
      role: "Business Korean Tutor",
      image: "/images/faqih.png",
      bio: "Focuses on professional fluency and confidence for corporate communication.",
    },
    documentation: [
      "/Classes Documentation/KFB/IMG_5215.JPG",
      "/Classes Documentation/KFB/IMG_6548.JPG",
      "/Classes Documentation/KFB/IMG_6854.jpg",
      "/Classes Documentation/KFB/IMG_7354.JPG",
      "/Classes Documentation/KFB/IMG_7803.JPG",
      "/Classes Documentation/KFB/IMG_8093.JPG",
    ],
  },
  "digital-business": {
    title: "Digital Business",
    image: "/Classes Documentation/DB/IMG_5308.JPG",
    level: "All Levels",
    summary: "Learn practical digital marketing, branding, and growth strategies.",
    highlights: ["Branding basics", "Social media strategy", "Content planning", "Growth metrics"],
    schedule: "Sat",
    time: "13:00 - 17:00",
    duration: "14 weeks",
    location: "Mataram University",
    rating: 4.9,
    tutor: {
      name: "Always Looking for the Best Mentors",
      role: "Digital Business Mentor",
      image: "/images/reva.png",
      bio: "Guides students on practical growth tactics with hands-on assignments.",
    },
    documentation: [
      "/Classes Documentation/DB/IMG_5308.JPG",
      "/Classes Documentation/DB/IMG_6599.JPG",
      "/Classes Documentation/DB/IMG_7389.JPG",
      "/Classes Documentation/DB/IMG_7820.JPG",
      "/Classes Documentation/DB/IMG_8128.JPG",
      "/Classes Documentation/DB/IMG_8580.JPG",
    ],
  },
};

