export const CLASS_DETAILS = {
  "basic-korean": {
    title: "Basic Korean",
    image: "/ourProgramAssets/image 1.png",
    level: "Beginner",
    summary:
      "Start from Hangul to everyday phrases. The class focuses on pronunciation, basic grammar, and daily conversations.",
    highlights: ["Hangul mastery", "Daily expressions", "Pronunciation drills", "Interactive roleplay"],
    schedule: "Mon & Wed",
    time: "18:30 - 20:00",
    duration: "8 weeks",
    location: "Hamkke Center, Room 201",
    price: "Rp. 150.000 / class",
    rating: 4.9,
    tutor: {
      name: "Fitry A.",
      role: "Korean Language Tutor",
      image: "/images/fitry.png",
      bio: "Specializes in beginner learners with engaging, step-by-step lessons and speaking practice.",
    },
    documentation: [
      "/ourProgramAssets/image 1.png",
      "/ourProgramAssets/image 4.png",
      "/ourProgramAssets/image 5.png",
    ],
  },
  "eps-topik": {
    title: "EPS TOPIK",
    image: "/ourProgramAssets/image 4.png",
    level: "Intermediate",
    summary: "Focused EPS-TOPIK preparation with targeted practice and structured guidance.",
    highlights: ["Mock tests", "Grammar clinics", "Listening drills", "Exam strategies"],
    schedule: "Tue & Thu",
    time: "18:30 - 20:30",
    duration: "10 weeks",
    location: "Hamkke Center, Room 305",
    price: "Rp. 175.000 / class",
    rating: 4.8,
    tutor: {
      name: "Jim K.",
      role: "TOPIK Coach",
      image: "/images/jim.png",
      bio: "Exam-oriented coach with a focus on timing, accuracy, and TOPIK question patterns.",
    },
    documentation: [
      "/ourProgramAssets/image 4.png",
      "/ourProgramAssets/kfb.png",
      "/ourProgramAssets/image 1.png",
    ],
  },
  "korean-for-tourism": {
    title: "Korean for Tourism",
    image: "/ourProgramAssets/image 4.png",
    level: "Beginner - Intermediate",
    summary: "Practical Korean for guiding, hospitality, and travel-related services.",
    highlights: ["Service phrases", "Tour guiding", "Customer handling", "Situational dialogs"],
    schedule: "Sat",
    time: "09:00 - 11:30",
    duration: "6 weeks",
    location: "Hamkke Center, Room 108",
    price: "Rp. 160.000 / class",
    rating: 4.7,
    tutor: {
      name: "Nad A.",
      role: "Tourism Language Tutor",
      image: "/images/nad.png",
      bio: "Emphasizes scenario-based learning to build confidence in real-world tourism settings.",
    },
    documentation: [
      "/ourProgramAssets/image 5.png",
      "/ourProgramAssets/image 1.png",
      "/ourProgramAssets/image 4.png",
    ],
  },
  "korean-for-business": {
    title: "Korean for Business",
    image: "/ourProgramAssets/kfb.png",
    level: "Intermediate",
    summary: "Professional Korean for workplace communication, meetings, and formal writing.",
    highlights: ["Business emails", "Meeting phrases", "Presentation practice", "Formal vocabulary"],
    schedule: "Fri",
    time: "19:00 - 21:00",
    duration: "8 weeks",
    location: "Hamkke Center, Room 302",
    price: "Rp. 180.000 / class",
    rating: 4.8,
    tutor: {
      name: "Faqih R.",
      role: "Business Korean Tutor",
      image: "/images/faqih.png",
      bio: "Focuses on professional fluency and confidence for corporate communication.",
    },
    documentation: [
      "/ourProgramAssets/kfb.png",
      "/ourProgramAssets/image 5.png",
      "/ourProgramAssets/image 4.png",
    ],
  },
  "digital-business": {
    title: "Digital Business",
    image: "/ourProgramAssets/image 5.png",
    level: "All Levels",
    summary: "Learn practical digital marketing, branding, and growth strategies.",
    highlights: ["Branding basics", "Social media strategy", "Content planning", "Growth metrics"],
    schedule: "Sun",
    time: "10:00 - 12:00",
    duration: "6 weeks",
    location: "Hamkke Center, Room 101",
    price: "Rp. 150.000 / class",
    rating: 4.9,
    tutor: {
      name: "Reva P.",
      role: "Digital Business Mentor",
      image: "/images/reva.png",
      bio: "Guides students on practical growth tactics with hands-on assignments.",
    },
    documentation: [
      "/ourProgramAssets/image 5.png",
      "/ourProgramAssets/image 1.png",
      "/ourProgramAssets/kfb.png",
    ],
  },
};
